version: '3.8'

services:
  selenium_app:
    build:
      context: .
      dockerfile: Dockerfile_selenium  
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
    network_mode: "host"  
    depends_on:
      - redis
    mem_limit: 4g


  notifier:
    build:
      context: .
      dockerfile: Dockerfile_notifier  
    network_mode: "host"  
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis_itop
    volumes:
      - redis-data:/data  
    network_mode: "host"  

volumes:
  redis-data:  
