#J'utilise une image python car je peux ajouter des dépendances contrairement à l'image selenium
FROM python:3.13-slim

# Installer les dépendances nécessaires pour Chromium, wget, et unzip
# J'utilise chromium car la derniere version de Chrome n'a pas de webdriver compatible (pour l'instant)
RUN apt-get update && \
    apt-get install -y wget unzip chromium chromium-driver fonts-liberation libasound2 libatk-bridge2.0-0 \
    libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libcurl4 libdbus-1-3 libdrm2 libexpat1 libgbm1 \
    libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libvulkan1 libx11-6 libxcb1 libxcomposite1 \
    libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils && \
    rm -rf /var/lib/apt/lists/*

# Je créé le lien symbolique
RUN ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

# Installation des dépendances beautiful soup et selenium
COPY requirements_selenium.txt /tmp/requirements_selenium.txt
RUN pip install -r /tmp/requirements_selenium.txt

# On copie le script dans l'image docker
COPY app.py /app.py

# Je définis les variables d'environnement
ENV CHROME_BIN=/usr/bin/chromium
ENV CHROMEDRIVER_PATH=/usr/local/bin/chromedriver

# On éxecute
CMD ["python", "/app.py"]
